name: Data Robot - Agro Logistics

on:
  schedule:
    # Roda a cada 1 hora (no minuto 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Permite que você clique em um botão para rodar na hora que quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=100 --no-cache-dir -r requirements.txt

      - name: Rodar o Robô de Dados
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VC_API_KEY: ${{ secrets.VC_API_KEY }}
          # Passamos o segredo direto para uma variável de ambiente
          GCP_JSON_DATA: ${{ secrets.GCP_SA_JSON }}
        run: |
          # O "echo" com aspas duplas preserva a estrutura do JSON
          echo "$GCP_JSON_DATA" > gcp_key.json
          
          # Definimos a variável que o Google Cloud SDK procura automaticamente
          export GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json
          
          # Roda o robô
          python worker.py
          
          # Remove a chave por segurança após o uso
          rm gcp_key.json