name: BigQuery Maintenance

on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch: 

jobs:
  refresh-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Atualizado para 3.11 (mais estável e sem avisos)

      - name: Install dependencies
        run: pip install google-cloud-bigquery pandas db-dtypes python-dotenv # Adicionado python-dotenv

      - name: Run Maintenance Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SA_JSON }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json
          python maintenance.py
          rm gcp_key.json